version: '3.5'

services:
  qad_php:
    build:
      context: .
    volumes:
      - ./www:/var/www
    ports:
      - 1205:80
  qad_db:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: phppass